version: '3.8'

services:
  web:
    image: hundreacrerealm-web:latest
    container_name: hundred-acre-realm
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - DATABASE_URL=file:/app/prisma/prod.db
    volumes:
      - ./uploads:/app/uploads
      - ./public:/app/public
      - ./prisma/prod.db:/app/prisma/prod.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 