services:
  app:
    build: .
    container_name: hundred-acre-realm
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./uploads:/app/uploads
      - ./public:/app/public
      - ./coregamedata:/app/coregamedata
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 